### ISSUE TITLE
IP blocking

### ISSUE THREAD

**Issue by shishir36** [foo-git/rewe-discounts#12] opened 2023-05-11 09:29 UTC
Rewe blocks the IP after few queries. Is there any way around to solve this issue ?

**Comment by foo-git** [comment] 2023-05-13 19:27
Do you know when the block is triggered, i.e. how many requests in a certain time?
When is the block released, e.g. after 24h?

I did not run into this limit during developing/testing/using it, so I'm not very keen on implementing evasion techniques, changing the IP address is out of scope at the moment.

**Comment by shishir36** [comment] 2023-05-14 00:50
I run this once a week. After 2 months I am facing this issue. Any advice ?

**Comment by foo-git** [comment] 2023-05-14 06:28
Strange, I also run it at least once a week for multiple months. I just checked, and the program runs fine.

Can you provide me the error messages or the traceback the program gives you?

**Comment by shishir36** [comment] 2023-05-15 09:27
ERROR Expecting value: line 1 column 1 (char 0)

well, it returns a bad response "forbidden 403" which later cannot be parsed as json so it show previous error. And same thing happens when I make this req from an EC2 instance. Any idea why these happen ?

**Comment by foo-git** [comment] 2023-05-18 07:02
Please try the new version of the script in the branch `fix_403` which mainly includes better error handling to aid debugging and post the error messages.

Right now I think it's a problem on your end as I can't reproduce it. Please double-check that your dependencies like cloudscraper are correctly installed and that the parameters for starting your program don't contain any typos.

**Comment by foo-git** [comment] 2023-06-09 05:54
Duplicate of #14, more details there, closing issue.

**Closed by foo-git** 2023-06-09 05:54 UTC
Labels: question

**Comment by foo-git** [comment] 2023-06-09 07:25
@shishir36: Please try the solution in #14, namely pinning the cloudscraper version to 1.2.69. This fixed the issue for at least two people. If it does not work, please re-open #14.
