### ISSUE TITLE
No discounts received - API changed?

### ISSUE THREAD

**Issue by olant** [foo-git/rewe-discounts#17] opened 2024-02-19 21:31 UTC
When trying to receive the current list I get:
```
(meins) root@dagobert:~/rewe-discounts# python3 rewe_discounts/rewe_discounts.py --market-id 1761063 --output-file "bla.md"
Traceback (most recent call last):
  File "/root/meins/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/rewe-discounts/rewe_discounts/rewe_discounts.py", line 194, in <module>
    data = scraper.get(url).json()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/meins/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
FAIL: Unknown error while fetching discounts from https://mobile-api.rewe.de/api/v3/all-offers?marketCode=1761063, maybe a typo or the server rejected the request.
(meins) root@dagobert:~/rewe-discounts#

```

**Comment by foo-git** [comment] 2024-02-20 07:07
Hi, I think this is a duplicate of #14, please try the solution mentioned in https://github.com/foo-git/rewe-discounts/issues/14#issuecomment-1939615326, basically trying out the testing branch.

**Comment by olant** [comment] 2024-02-25 19:42
Unfortunaltely using the testing branch did not help:

```
(rewe-test) root@dagobert:~/rewe-test/rewe-discounts/rewe_discounts# pip list
Package            Version
------------------ --------
certifi            2024.2.2
charset-normalizer 3.3.2
cloudscraper       1.2.69
idna               3.6
pip                23.0.1
pyparsing          3.1.1
requests           2.31.0
requests-toolbelt  1.0.0
setuptools         66.1.1
urllib3            2.2.1
(rewe-test) root@dagobert:~/rewe-test/rewe-discounts/rewe_discounts# python3 rewe_discounts.py  --market-id 1761063 --output-file "Rewe.md"
INFO: Unknown error while fetching discounts from https://mobile-api.rewe.de/api/v3/all-offers?marketCode=1761063, using less-elegant approach now.
Traceback (most recent call last):
  File "/root/rewe-test/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 321, in <module>
    data = scraper.get(url).json()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/rewe-test/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 162, in get_product_details
    Product.base_price = item['pricing']['basePrice']
    ^^^^^^^^^^^^^^^^^^
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 71, in base_price
    self._base_price = clean_string(base_price)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 120, in clean_string
    output = (input.replace('\n', ' ').replace('\u2028', ' ')
              ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 329, in <module>
    data = less_elegant_query(market_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 200, in less_elegant_query
    get_product_details(NewProduct)
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 164, in get_product_details
    Product.base_price = item['amount']
    ^^^^^^^^^^^^^^^^^^
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 71, in base_price
    self._base_price = clean_string(base_price)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/rewe-test/rewe-discounts/rewe_discounts/rewe_discounts.py", line 120, in clean_string
    output = (input.replace('\n', ' ').replace('\u2028', ' ')
              ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'

```

Anything else I can try or provide?

**Comment by olant** [comment] 2024-02-25 20:37
Yes, this is working now! Thanks :)

**Comment by foo-git** [comment] 2024-02-25 20:41
No worries, thanks for your valuable feedback.

**Closed by foo-git** 2024-02-25 20:41 UTC
Labels: bug
